/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.zookeeper.server.token;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Arrays;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.security.sasl.SaslException;
import org.apache.zookeeper.common.Time;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Computes and validates delegation token credentials.
 *
 * <p>The token password is never stored: any ensemble member derives it as
 * HMAC-SHA256(masterKey, identifierBytes). The master key is either static —
 * shared by the whole ensemble via the file named by
 * {@code zookeeper.tokenAuth.secretFile} and referenced by tokens as key id
 * {@link #STATIC_KEY_ID} — or, with {@code zookeeper.tokenAuth.keyRotationEnabled},
 * generated by the leader, rolled every {@code zookeeper.tokenAuth.keyRollIntervalMs}
 * and replicated in the token store; tokens then reference the signing key by
 * its id in the identifier.
 *
 * <p>Validation here covers only the identifier lifetime ({@code maxDate}).
 * Revocation checks arrive with the token store.
 */
public class DelegationTokenSecretManager {

    public static final String TOKEN_AUTH_ENABLED = "zookeeper.tokenAuth.enabled";
    public static final String TOKEN_AUTH_SECRET_FILE = "zookeeper.tokenAuth.secretFile";
    public static final String TOKEN_AUTH_RENEW_INTERVAL = "zookeeper.tokenAuth.renewIntervalMs";
    public static final String TOKEN_AUTH_MAX_LIFETIME = "zookeeper.tokenAuth.maxLifetimeMs";
    public static final String TOKEN_AUTH_KEY_ROTATION_ENABLED = "zookeeper.tokenAuth.keyRotationEnabled";
    public static final String TOKEN_AUTH_KEY_ROLL_INTERVAL = "zookeeper.tokenAuth.keyRollIntervalMs";

    public static final long DEFAULT_RENEW_INTERVAL_MS = 24L * 60 * 60 * 1000;
    public static final long DEFAULT_MAX_LIFETIME_MS = 7L * 24 * 60 * 60 * 1000;
    public static final long DEFAULT_KEY_ROLL_INTERVAL_MS = 24L * 60 * 60 * 1000;

    /** Key id reserved for the static master key from the secret file. */
    public static final int STATIC_KEY_ID = 1;

    /** Lowest id ever assigned to a generated (rotated) key. */
    public static final int FIRST_GENERATED_KEY_ID = STATIC_KEY_ID + 1;

    private static final Logger LOG = LoggerFactory.getLogger(DelegationTokenSecretManager.class);
    private static final String HMAC_ALGORITHM = "HmacSHA256";
    private static final int MIN_KEY_LENGTH = 16;
    private static final int GENERATED_KEY_LENGTH = 32;

    private static final SecureRandom KEY_RANDOM = new SecureRandom();

    private final SecretKeySpec masterKey;
    private final long renewIntervalMs;
    private final long maxLifetimeMs;
    private final boolean keyRotationEnabled;
    private final long keyRollIntervalMs;

    public DelegationTokenSecretManager(byte[] masterKey) {
        this(masterKey, Boolean.getBoolean(TOKEN_AUTH_KEY_ROTATION_ENABLED));
    }

    public DelegationTokenSecretManager(byte[] masterKey, boolean keyRotationEnabled) {
        if (masterKey == null && !keyRotationEnabled) {
            throw new IllegalArgumentException("token master key required when key rotation is disabled");
        }
        if (masterKey != null && masterKey.length < MIN_KEY_LENGTH) {
            throw new IllegalArgumentException("token master key must be at least " + MIN_KEY_LENGTH + " bytes");
        }
        this.masterKey = masterKey == null ? null : new SecretKeySpec(masterKey, HMAC_ALGORITHM);
        this.renewIntervalMs = Long.getLong(TOKEN_AUTH_RENEW_INTERVAL, DEFAULT_RENEW_INTERVAL_MS);
        this.maxLifetimeMs = Long.getLong(TOKEN_AUTH_MAX_LIFETIME, DEFAULT_MAX_LIFETIME_MS);
        this.keyRotationEnabled = keyRotationEnabled;
        this.keyRollIntervalMs = Long.getLong(TOKEN_AUTH_KEY_ROLL_INTERVAL, DEFAULT_KEY_ROLL_INTERVAL_MS);
    }

    public long getRenewIntervalMs() {
        return renewIntervalMs;
    }

    public long getMaxLifetimeMs() {
        return maxLifetimeMs;
    }

    public boolean isKeyRotationEnabled() {
        return keyRotationEnabled;
    }

    public long getKeyRollIntervalMs() {
        return keyRollIntervalMs;
    }

    public boolean hasStaticKey() {
        return masterKey != null;
    }

    public byte[] generateKeyBytes() {
        byte[] key = new byte[GENERATED_KEY_LENGTH];
        KEY_RANDOM.nextBytes(key);
        return key;
    }

    /**
     * Expiry of a key created now: it must outlive the max date of every token
     * it can sign, i.e. tokens issued until the next roll.
     */
    public long newKeyExpiry(long now) {
        return now + keyRollIntervalMs + maxLifetimeMs;
    }

    /**
     * Returns whether token authentication is enabled via {@code zookeeper.tokenAuth.enabled}.
     */
    public static boolean isEnabled() {
        return Boolean.getBoolean(TOKEN_AUTH_ENABLED);
    }

    /**
     * Creates a manager from system properties, or returns null when token
     * authentication is disabled.
     *
     * @throws IOException if enabled but the secret file is missing or unusable,
     *         so a misconfigured server fails at startup instead of silently
     *         rejecting tokens
     */
    public static DelegationTokenSecretManager createIfEnabled() throws IOException {
        if (!isEnabled()) {
            return null;
        }
        boolean rotation = Boolean.getBoolean(TOKEN_AUTH_KEY_ROTATION_ENABLED);
        String secretFile = System.getProperty(TOKEN_AUTH_SECRET_FILE);
        if (secretFile == null || secretFile.isEmpty()) {
            if (!rotation) {
                throw new IOException(
                    TOKEN_AUTH_ENABLED + " is set but " + TOKEN_AUTH_SECRET_FILE + " is not configured");
            }
            LOG.info("Delegation token authentication enabled with rotated master keys");
            return new DelegationTokenSecretManager(null, true);
        }
        byte[] key = readSecretFile(secretFile);
        LOG.info("Delegation token authentication enabled, master key loaded from {}{}",
            secretFile, rotation ? ", key rotation on" : "");
        return new DelegationTokenSecretManager(key, rotation);
    }

    /**
     * Reads the key as raw bytes — a binary file (e.g. openssl rand output)
     * must not be altered by charset round-trips. Only leading and trailing
     * ASCII whitespace is stripped, so text keys keep their old value.
     */
    static byte[] readSecretFile(String path) throws IOException {
        byte[] raw = Files.readAllBytes(Paths.get(path));
        int start = 0;
        int end = raw.length;
        while (start < end && isAsciiWhitespace(raw[start])) {
            start++;
        }
        while (end > start && isAsciiWhitespace(raw[end - 1])) {
            end--;
        }
        if (end - start < MIN_KEY_LENGTH) {
            throw new IOException("token master key in " + path + " is shorter than " + MIN_KEY_LENGTH + " bytes");
        }
        return Arrays.copyOfRange(raw, start, end);
    }

    private static boolean isAsciiWhitespace(byte b) {
        return b == ' ' || b == '\n' || b == '\r' || b == '\t';
    }

    /**
     * Derives the token password for the given serialized identifier using the
     * static master key.
     */
    public byte[] computePassword(byte[] identifierBytes) {
        if (masterKey == null) {
            throw new IllegalStateException("no static master key configured");
        }
        return hmac(masterKey, identifierBytes);
    }

    /**
     * Derives the token password for the given serialized identifier using an
     * explicit (rotated) key.
     */
    public static byte[] computePassword(byte[] keyBytes, byte[] identifierBytes) {
        return hmac(new SecretKeySpec(keyBytes, HMAC_ALGORITHM), identifierBytes);
    }

    private static byte[] hmac(SecretKeySpec key, byte[] identifierBytes) {
        try {
            Mac mac = Mac.getInstance(HMAC_ALGORITHM);
            mac.init(key);
            return mac.doFinal(identifierBytes);
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new IllegalStateException(HMAC_ALGORITHM + " unavailable", e);
        }
    }

    /**
     * Checks that the token is still within its lifetime.
     *
     * @throws SaslException if the token has expired
     */
    public void validate(DelegationTokenIdentifier ident) throws SaslException {
        long now = Time.currentWallTime();
        if (now > ident.getMaxDate()) {
            throw new SaslException("delegation token for " + ident.getOwner()
                + " expired at " + ident.getMaxDate() + " (now " + now + ")");
        }
    }

}
